# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Site settings
title: Hinduphil
description: A blog about Hinduism, Indian culture, and more
# baseurl: /
author:
  name: Shekhar Devm Upadhyay

# Navigation links
# nav_links:
#   - title: Home
#     url: /index.md
#   - title: About Me
#     url: /_posts/2023-09-06-who-am-i.md
  # - title: About
  #   url: /about.html
  # - title: Contact
  #   url: /contact.html

# Social media links
social_links:
  - title: Twitter
    url: https://twitter.com/DevmShekhar
  - title: GitHub
    url: https://github.com/NinjaTuna007
  - title: LinkedIn
    url: https://www.linkedin.com/in/sdupadhyay/

# Build settings for GitHub Pages
# remote_theme: "mmistakes/minimal-mistakes"
# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag
#   - jekyll-redirect-from
#   - jekyll-sitemap
#   - jekyll-remote-theme

# Exclude files from build
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - README.md
#   - LICENSE
#   - node_modules
#   - vendor
#   - _config.yml
#   - .gitignore
#   - .github

# # Permalinks
# permalink: /:categories/:title/

# # # Pagination
# paginate: 5
# paginate_path: "/page:num/"

# # Categories
# defaults:
#   - scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: "post"
#       author_profile: true
#       share: true
#       related: true
#       comments: true
#       categories: ["uncategorized"]
#   - scope:
#       path: ""
#       type: "pages"
#     values:
#       layout: "page"
#       author_profile: true
#       share: true
#       related: true
#       comments: true
#       categories: ["uncategorized"]